version: '3.9'
services:
  api:
    environment:
      - STORAGE_BACKEND=s3
      - S3_BUCKET=vfr
      - S3_REGION=us-east-1
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_PREFIX=vfr/
      - RESULT_REDIRECT=1
    depends_on:
      - minio
      - minio_setup

  celery_worker:
    environment:
      - STORAGE_BACKEND=s3
      - S3_BUCKET=vfr
      - S3_REGION=us-east-1
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_PREFIX=vfr/
