version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: vfr
      POSTGRES_PASSWORD: vfr
      POSTGRES_DB: vfr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=postgresql+psycopg://vfr:vfr@postgres:5432/vfr
      - VFR_CONFIG=/app/configs/pipeline.yaml
    depends_on:
      - redis
      - postgres
    command: ["celery", "-A", "backend.app.tasks", "worker", "-l", "INFO"]

volumes:
  pgdata:

