FROM python:3.10-slim
# syntax=docker/dockerfile:1.5

WORKDIR /app

COPY requirements.txt requirements-ml.txt ./
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt && \
    pip install -r requirements-ml.txt

COPY . .

RUN chmod +x docker/api-entrypoint.sh && mkdir -p storage

ENV PYTHONUNBUFFERED=1

EXPOSE 8000
CMD ["docker/api-entrypoint.sh"]
