FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements-ml.txt ./
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements-ml.txt

COPY . .

RUN chmod +x docker/api-entrypoint.sh && mkdir -p storage

ENV PYTHONUNBUFFERED=1

EXPOSE 8000
CMD ["docker/api-entrypoint.sh"]
