# Define model artifacts to prefetch (download once) on startup if PREFETCH_MODELS=1
# Each item: name, version, sha256, and either url or s3_uri. Optionally unpack: true.

artifacts:
  - name: yolo_v8_pose
    version: v8n
    url: https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n-pose.pt
    unpack: false
  - name: yolo_v8_pose
    version: v8x
    url: https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8x-pose.pt
    unpack: false
  - name: realesrgan
    version: x4plus
    url: https://github.com/xinntao/Real-ESRGAN/releases/download/v0.3.0/RealESRGAN_x4plus.pth
    unpack: false
  - name: swinir
    version: x4
    # Provide your own URL/S3 for SwinIR x4 weights if you want this upscaler
    # url: https://...
    # s3_uri: s3://...
    unpack: false
  - name: codeformer
    version: v0.1.0
    url: https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth
    unpack: false
  - name: ip_adapter
    version: sdxl
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter_sdxl.bin
    unpack: false
  - name: ip_adapter_plus
    version: sdxl_vit_h
    url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/ip-adapter-plus_sdxl_vit-h.bin
    unpack: false
  - name: ip_adapter_faceid_plusv2_lora
    version: sdxl
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sdxl_lora.safetensors
    sha256: f24b4bb2dad6638a09c00f151cde84991baf374409385bcbab53c1871a30cb7b
    unpack: false
  - name: instantid_antelopev2
    version: v1
    url: https://huggingface.co/MonsterMMORPG/tools/resolve/main/antelopev2.zip
    unpack: true
  - name: instantid_controlnet
    version: v1
    url: https://huggingface.co/InstantX/InstantID/resolve/main/ControlNetModel/diffusion_pytorch_model.safetensors
    unpack: false
  - name: instantid_ip_adapter
    version: v1
    url: https://huggingface.co/InstantX/InstantID/resolve/main/ip-adapter.bin
    unpack: false
  - name: rvm_mobilenetv3
    version: v1
    url: https://github.com/PeterL1n/RobustVideoMatting/releases/download/v1.0/rvm_mobilenetv3.pth
    unpack: false
  - name: midas_dpt_large
    version: v3
    url: https://github.com/isl-org/MiDaS/releases/download/v3/dpt_large-midas-2f21e586.pt
    unpack: false
  - name: big_lama
    version: v1
    url: https://huggingface.co/saic-mdal/Big-LaMA/resolve/main/big-lama.pt
    unpack: false
  - name: omnidata_normals
    version: v1
    # Provide URL/S3 for Omnidata normals model (for high-quality normal control)
    # url: https://...
    # s3_uri: s3://...
    unpack: false
# - name: stable_viton
#   version: v1
#   sha256: "<sha256>"
#   s3_uri: "s3://my-bucket/path/to/stable_viton_v1.tar.gz"
#   unpack: true
# - name: smplx
#   version: v1
#   sha256: "<sha256>"
#   s3_uri: "s3://my-bucket/path/to/smplx_models.tar.gz"
#   unpack: true
  - name: schp_lip
    version: 20190826
    url: https://huggingface.co/levindabhi/Self-Correction-Human-Parsing/resolve/main/exp-schp-201908261155-lip.pth
    unpack: false
  - name: schp_cihp
    version: 20190826
    url: https://huggingface.co/levindabhi/Self-Correction-Human-Parsing/resolve/main/exp-schp-201908261155-cihp.pth
    unpack: false
  - name: openpose_caffe
    version: body_25
    url: https://huggingface.co/camenduru/openpose/resolve/f5bb0c0a16060ac8b373472a5456c76bd68eb202/pose_iter_440000.caffemodel
    unpack: false
# - name: ghum
#   version: v1
#   sha256: "<sha256>"
#   s3_uri: "s3://my-bucket/path/to/ghum_models.tar.gz"
#   unpack: true
# - name: openpose_models
#   version: v1
#   sha256: "<sha256>"
#   s3_uri: "s3://my-bucket/path/to/openpose_models.zip"
#   unpack: true
# - name: gp_vton
#   version: v1
#   sha256: "<sha256>"
#   s3_uri: "s3://my-bucket/path/to/gp_vton_weights.tar.gz"
#   unpack: true
# - name: recloth_viton
#   version: v1
#   sha256: "<sha256>"
#   s3_uri: "s3://my-bucket/path/to/recloth_viton_weights.tar.gz"
#   unpack: true
# - name: bgm_v2
#   version: v1
#   sha256: "<sha256>"
#   s3_uri: "s3://my-bucket/path/to/background_matting_v2.pth"
#   unpack: false

hf_models:
  # SDXL base/refiner + turbo + flux
  - stabilityai/stable-diffusion-xl-base-1.0
  - stabilityai/stable-diffusion-xl-refiner-1.0
  - stabilityai/sdxl-turbo
  - black-forest-labs/FLUX.1-dev
  # SDXL ControlNets (canny/openpose/depth/normal/seg)
  - diffusers/controlnet-canny-sdxl-1.0
  - diffusers/controlnet-openpose-sdxl-1.0
  - diffusers/controlnet-depth-sdxl-1.0
  - diffusers/controlnet-normal-sdxl-1.0
  - diffusers/controlnet-seg-sdxl-1.0
  # IP-Adapter FaceID models
  - h94/IP-Adapter-FaceID
  # ControlNet SD1.5 (for auxiliary checks/tools)
  - lllyasviel/sd-controlnet-openpose
  - lllyasviel/sd-controlnet-depth
  - lllyasviel/control_v11p_sd15_normalbae
  - lllyasviel/sd-controlnet-canny
  # ControlNet Union SDXL
  - xinsir/controlnet-union-sdxl-1.0
  - lllyasviel/Annotators
  - patrickjohncyh/fashion-clip
  - Marqo/marqo-fashionCLIP
