# Define model artifacts to prefetch (download once) on startup if PREFETCH_MODELS=1
# Each item: name, version, sha256 (optional), and either url or s3_uri. Optionally unpack: true.

artifacts:
  # --- Pose (best-of) ---
  - name: yolo_v8_pose
    version: v8x
    url: https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8x-pose.pt
    unpack: false

  # --- Upscale / face restore ---
  - name: realesrgan
    version: x4plus
    url: https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth
    unpack: false
  - name: codeformer
    version: v0.1.0
    url: https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth
    unpack: false

  # --- IP-Adapter & FaceID (SDXL) ---
  - name: ip_adapter_faceid_plusv2_lora
    version: sdxl
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sdxl_lora.safetensors
    sha256: f24b4bb2dad6638a09c00f151cde84991baf374409385bcbab53c1871a30cb7b
    unpack: false
  - name: ip_adapter_faceid_plusv2_bin
    version: sdxl
    url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plusv2_sdxl.bin
    unpack: false

  # --- InstantID (optional but kept) ---
  - name: instantid_antelopev2_bundle
    version: v1
    url: https://huggingface.co/MonsterMMORPG/tools/resolve/main/antelopev2.zip
    unpack: true
  - name: instantid_controlnet
    version: v1
    url: https://huggingface.co/InstantX/InstantID/resolve/main/ControlNetModel/diffusion_pytorch_model.safetensors
    unpack: false
  - name: instantid_ip_adapter
    version: v1
    url: https://huggingface.co/InstantX/InstantID/resolve/main/ip-adapter.bin
    unpack: false

  # --- Matting ---
  - name: rvm_mobilenetv3
    version: v1.0.0
    url: https://github.com/PeterL1n/RobustVideoMatting/releases/download/v1.0.0/rvm_mobilenetv3.pth
    unpack: false

  # --- Depth (best-of) ---
  - name: zoedepth_m12_nk
    version: v1
    url: https://huggingface.co/ckpt/ControlNet-v1-1/resolve/main/ZoeD_M12_NK.pt
    unpack: false

  # --- Garment UV/inpaint + coarse mesh + fabric classifier ---
  - name: clip_vit_l14
    version: v1
    url: https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/pytorch_model.bin
    unpack: false

  # --- Segmentation (pick one; we use LIP) ---
  - name: schp_lip
    version: 20190826
    url: https://huggingface.co/levihsu/ced/resolve/main/exp-schp-201908261155-lip.pth
    unpack: false

  # --- SDXL base/refiner (local-file loading) ---
  - name: sdxl_base
    version: 1.0
    url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors
    unpack: false
  - name: sdxl_refiner
    version: 1.0
    url: https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors
    unpack: false

  # --- (Optional) OpenPose Caffe (only if you enable it)
  # - name: openpose_caffe
  #   version: body_25
  #   url: https://huggingface.co/camenduru/openpose/resolve/f5bb0c0a16060ac8b373472a5456c76bd68eb202/pose_iter_440000.caffemodel
  #   unpack: false

hf_models:
  # Required for HED / NormalBae / Zoe / OpenPose annotators (control maps)
  - lllyasviel/Annotators
  # ControlNet-Union SDXL needs a full local snapshot folder (configs + weights)
  - xinsir/controlnet-union-sdxl-1.0
  # Snapshot IP-Adapter repos to avoid fragile direct-file links
  - h94/IP-Adapter
  - h94/IP-Adapter-FaceID
  # LaMa (Big-Lama) snapshot for UV inpainting weights
  - saic-mdal/LaMa
  # TripoSR snapshot (coarse clothed human mesh)
  - stabilityai/TripoSR
