# Baseline hyperparameters and I/O contracts derived from the requirements PDF.

finisher:
  denoise: 0.12  # Lower to preserve details
  steps: 50
  cfg: 6.2
  res_long: 1344
  backend: sdxl_controlnet  # local | kling | remote | sdxl | flux | sdxl_controlnet
  escalate_on_fail: false
  ctrl:
    pose: 0.90
    depth: 0.60
    normal: 0.50
    seg: 0.35
    edge: 0.40
  adapters:
    garment: 1.00
    faceid: 0.85
  refiner_denoise: 0.14
  tilepass_denoise: 0.12
  tilepass_steps: 16

io_contracts:
  user_canonicalization:
    in: ["RGB image(s) >=1024px"]
    out: ["smplx_mesh:OBJ/NPZ", "uv_texture:PNG", "masks:PNG", "keypoints:JSON"]
  garment_assetization:
    in: ["front photo", "side photo?", "fabric tag"]
    out: ["mesh:OBJ", "uv:PNG", "texture:PNG"]
  draping:
    in: ["body mesh", "garment mesh", "pose"]
    out: ["draped mesh", "collision map:NPZ"]
  finisher:
    in: ["soft render:PNG", "control maps:PNG", "adapters:features"]
    out: ["final:PNG/JPEG"]

vton:
  enabled: true
  provider: stableviton  # local | stableviton | remote

providers:
  segmentation: local  # local | torchvision | remote
  pose: yolov8  # mediapipe | yolov8 | remote
  geometry: smplx  # stub | smplx | remote

post:
  upscaler: realesrgan  # none | realesrgan
  face_restore: false

qa_thresholds:
  garment_fidelity_clip_min: 0.28
  garment_fidelity_lpips_max: 0.32
  aesthetics_min: 0.58
  identity_min: 0.75
  iou_garment_skin_min: 0.90
  retry:
    max_retries: 1
    step_increase: 5
    garment_adapter_delta: 0.05
    denoise_delta: -0.02
